server:
  port: 8080 # 项目启动端口

spring:
  profiles:
    active: dev # 激活 dev 开发环境
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小限制
      max-request-size: 10MB # 总请求大小限制

logging:
  config: classpath:log4j2.xml # 设置日志配置文件路径


